sudo: required
dist: trusty

# travis-ci does not have first-class support for octave
language: generic

python:
  - "2.7"
  - "3.4"

env:
- OCT_PPA=octave/stable

# not on trusty: http://ppa.launchpad.net/dac922/octave-unstable/ubuntu/pool/main/o/octave/
#- OCT_PPA=dac922/octave-unstable

before_install:
  - sudo pip install -U pytest

install:
  - export
  - if [ "x$OCT_PPA" != "x" ]; then
        sudo apt-add-repository -y ppa:$OCT_PPA;
        sudo apt-get update -qq;
        sudo apt-get install -qq -y octave liboctave-dev;
    fi

# command to run tests
script:
  - pushd python && py.test -s && popd
  - pushd matlab && octave --eval hello
